# Generated by Django 3.2.6 on 2021-09-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField()),
                ('title', models.CharField(default='Task title mask(please change it)', max_length=100)),
                ('description', models.TextField(default='Should be done!')),
                ('state', models.CharField(choices=[('ready', 'Ready to execute'), ('in_progress', 'In progress'), ('done', 'done')], default='ready', max_length=50)),
            ],
            options={
                'ordering': ['create_date'],
            },
        ),
    ]
